# Generated by Django 4.2 on 2023-05-28 22:56

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteurs',
            name='pay',
            field=django_countries.fields.CountryField(default='+223', max_length=2),
        ),
    ]
