# Generated by Django 4.2 on 2023-05-28 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auteurs_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteurs',
            name='numero',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Contact invalide !', regex='^\\+?1?\\d{9, 15}$')]),
        ),
    ]
