# Generated by Django 4.2 on 2023-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_articles_commentaire_articles_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='commentaire',
            field=models.ManyToManyField(to='blog.commentaires'),
        ),
    ]
