# Generated by Django 4.2 on 2023-06-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_articles_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='commentaire',
            field=models.ManyToManyField(blank=True, null=True, to='blog.commentaires'),
        ),
    ]
