# Generated by Django 4.2 on 2023-06-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_articles_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(upload_to='articles_pictures/', verbose_name="Image d'illustration"),
        ),
    ]
