# Generated by Django 4.2.1 on 2023-05-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Projets')),
                ('img', models.ImageField(upload_to='project_img/')),
                ('describes', models.TextField(verbose_name='Description du projet')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
