# Generated by Django 4.2.1 on 2023-05-25 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_projects_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Nom du client')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom du client')),
                ('profil', models.CharField(max_length=50, verbose_name='Status du client')),
                ('tel', models.CharField(max_length=50, verbose_name='Numéro de télephone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse mail du client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Les Clients',
                'ordering': ['last_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Projet', 'verbose_name_plural': 'Les Projets'},
        ),
    ]
