# Generated by Django 4.2 on 2023-06-15 01:40

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommanderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(max_length=200)),
                ('raison_social', models.CharField(max_length=300)),
                ('domaine_dactivite', models.CharField(max_length=200)),
                ('adresse', django_countries.fields.CountryField(max_length=2)),
                ('ville', models.CharField(max_length=200)),
                ('nom_personne', models.CharField(max_length=200)),
                ('prenom_personne', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Ce n'est pas un serieux numéro de télephone !", regex='^(+){1}\\d{2,4}\\s?\\d{4,10}$')])),
                ('email', models.EmailField(max_length=254)),
                ('forme_du_projet', models.CharField(choices=[('creation_de_site', 'Création de site'), ('refonte_du_site', 'Refonte de site'), ('amelioration_du_site', 'Amélioration du site')], max_length=100)),
                ('refonte_true', models.URLField(blank=True)),
                ('nature_du_projet', models.CharField(choices=[('creation_de_site', 'Création de site'), ('refonte_du_site', 'Refonte de site'), ('amelioration_du_site', 'Amélioration du site')], max_length=100)),
            ],
        ),
    ]
