# Generated by Django 4.2 on 2023-05-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountsauth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsauth',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
