# Generated by Django 4.2 on 2023-05-31 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_accountsauth_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsauth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
